class Config:
    SECRET_KEY = 'APP SECRET KEY'
    TOKEN_SECRET = 'TOKEN SECRET KEY'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///notecraft.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    EMAIL_HOST = 'EMAIL SENDER HOST'
    EMAIL_KEY = 'EMAIL API KEY'
